name: create tags

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        type: string

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - run: |
          git tag "${{ inputs.version }}"
          git push origin "${{ inputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT}}
